exclude: 'docs|node_modules|migrations|config|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=88]

#-   repo: local
#    hooks:
#      - id: flake8
#        name: flake8
#        entry: flake8
#        language: python
#        types: [python]

