# Generated by Django 4.0.6 on 2022-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_total_in_stock_productentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productentry',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Entry', 'verbose_name_plural': 'Product Entry'},
        ),
        migrations.AddField(
            model_name='productentry',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
