# Generated by Django 4.0.6 on 2022-07-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productentry_options_productentry_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Entry', 'verbose_name_plural': 'Product Entry'},
        ),
    ]
