# Generated by Django 4.0.6 on 2022-07-17 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
