# Generated by Django 4.0.6 on 2022-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='202020', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('weekly_order_product', 'weekly order product'), ('custom', 'custom')], max_length=32),
        ),
    ]
